import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import Navbar from "../components/Navbar";
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

export default function Home({ exploreData, cardsData }) {
  const getMediumCardData = () => {
    return [
        {
          "name": "Villa Zara",
          "location": "Kalkan / Kördere",
          "capacity": 6,
          "bedrooms": 3,
          "bathrooms": 3,
          "price_per_night": "4.286 TL",
          "images": [
            "https://cdn.villamsec.com/uploads/410x260/1ZARDSE0046_992.jpg",
            "https://cdn.villamsec.com/uploads/410x260/1ZARDSE0052_18.jpg",
            "https://cdn.villamsec.com/uploads/410x260/1ZARDSE0048_251.jpg"
          ]
        },
        {
          "name": "Villa Zara Duo",
          "location": "Kalkan / Kördere",
          "capacity": 6,
          "bedrooms": 3,
          "bathrooms": 3,
          "price_per_night": "4.286 TL",
          "images": [
            "https://cdn.villamsec.com/uploads/410x260/2ZARDSE0050_267.jpg",
            "https://cdn.villamsec.com/uploads/410x260/2ZARDSE001_971.jpg",
            "https://cdn.villamsec.com/uploads/410x260/2ZARDSE0053_442.jpg"
          ]
        },
        {
          "name": "Villa Karbelen",
          "location": "Kalkan / Kördere",
          "capacity": 4,
          "bedrooms": 2,
          "bathrooms": 2,
          "price_per_night": "4.000 TL",
          "images": [
            "https://cdn.villamsec.com/uploads/410x260/iMG-20240203-WA0013_948.jpg",
            "https://cdn.villamsec.com/uploads/410x260/iMG-20240203-WA0014_146.jpg",
            "https://cdn.villamsec.com/uploads/410x260/iMG-20240203-WA0041_849.jpg"
          ]
        },
        {
          "name": "Villa Lokum",
          "location": "Kalkan / Çavdır",
          "capacity": 6,
          "bedrooms": 3,
          "bathrooms": 3,
          "price_per_night": "5.000 TL",
          "images": [
            "https://cdn.villamsec.com/uploads/410x260/DSC09186_87.jpg",
            "https://cdn.villamsec.com/uploads/410x260/DSC09208_38.jpg",
            "https://cdn.villamsec.com/uploads/410x260/DSC09245_267.jpg"
          ]
        },
        {
          "name": "Villa Manzara 1",
          "location": "Kalkan / Çavdır",
          "capacity": 4,
          "bedrooms": 2,
          "bathrooms": 2,
          "price_per_night": "4.000 TL",
          "images": [
            "https://cdn.villamsec.com/uploads/410x260/DSC_3952-Enhanced-NR_774.jpg",
            "https://cdn.villamsec.com/uploads/410x260/DSC_3951-Enhanced-NR_485.jpg",
            "https://cdn.villamsec.com/uploads/410x260/DSC_3948-Enhanced-NR_893.jpg"
          ]
        },
        {
          "name": "Villa Feel",
          "location": "Kalkan / Üzümlü",
          "capacity": 6,
          "bedrooms": 3,
          "bathrooms": 3,
          "price_per_night": "5.500 TL",
          "images": [
            "https://cdn.villamsec.com/uploads/410x260/DSC_1878_306.jpg",
            "https://cdn.villamsec.com/uploads/410x260/DSC_1872_renamed_27038_310.jpg",
            "https://cdn.villamsec.com/uploads/410x260/DSC_1843_renamed_16780_40.jpg"
          ]
        }
    ];
  };
  const categories = [
    { href: "/balayi-villalari", img: "https://cdn.villacim.com.tr/uploads/128/480_honeymoon.svg", title: "Balayı Villaları" },
    { href: "/2025-villalari", img: "https://cdn.villacim.com.tr/uploads/128/468_252_496_20242.png", title: "2025 Villaları" },
    { href: "/havuzu-korunakli-villalar", img: "https://cdn.villacim.com.tr/uploads/128/886_fences.svg", title: "Havuzu Korunaklı Villalar" },
    { href: "/isitmali-havuzlu", img: "https://cdn.villacim.com.tr/uploads/128/859_pool.svg", title: "Isıtmalı Havuzlu" },
    { href: "/denize-yakin-villalar", img: "https://cdn.villacim.com.tr/uploads/128/334_sunset.svg", title: "Denize Yakın Villalar" },
    { href: "/ekonomik-villalar", img: "https://cdn.villacim.com.tr/uploads/128/421_wallet.svg", title: "Ekonomik Villalar" },
    { href: "/jakuzili-villalar", img: "https://cdn.villacim.com.tr/uploads/128/807_jacuzi.svg", title: "Jakuzili Villalar" },
    { href: "/luks-villalar", img: "https://cdn.villacim.com.tr/uploads/128/129_diamond.svg", title: "Lüks Villalar" }
];
  
  const mediumCardData = getMediumCardData();
  return (
    <div className="">
      <Navbar />
      <Head>
        <title>InnElegance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo/favicon.ico" />
        </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Sana Özel Villalar</h2>
          {/* Pull some data from a server -API end points */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {categories.map((category, index) => (
        <SmallCard key={index} {...category} />
      ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Ultra Lüks Villaları Keşfet</h2>
          <div className="flex space-x-8 overflow-x-scroll scrollbar-hide p-8 -ml-8">
          {mediumCardData.map((data, index) => (
              <MediumCard
                key={index}
                location={data.location}
                name={data.name}
                images={data.images}
                title={data.title}
                capacity={data.capacity}
                bedrooms={data.bedrooms}
                bathrooms={data.bathrooms}
                price_per_night={data.price_per_night}
              />
            ))}
          </div>
        </section>
        <LargeCard
  img="https://www.villam365.com/site/sized/108081/2024/04/adobestock-293351623_1-4000x9000.webp"
  title="Inn Elegance"
  description="Konfor ve şıklığın buluştuğu özel konaklama deneyimi"
  buttonText="Şimdi Keşfedin"
/>
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );
  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
    (res) => res.json()
  );
  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
